#!/bin/bash
wget -O /usr/bin/datetime-sync https://raw.githubusercontent.com/andrygibhq/modwrt/raw/main/datetime-sync && chmod +x /usr/bin/datetime-sync
wget -O /usr/bin/freecron https://raw.githubusercontent.com/andrygibhq/modwrt/raw/main/freecron && chmod +x /usr/bin/freecron
wget -O /usr/bin/neofetch https://raw.githubusercontent.com/andrygibhq/modwrt/raw/main/neofetch && chmod +x /usr/bin/neofetch
wget -O /usr/bin/speedtest https://raw.githubusercontent.com/andrygibhq/modwrt/raw/main/speedtest && chmod +x /usr/bin/speedtest
wget -O /usr/bin/sysinfo https://raw.githubusercontent.com/andrygibhq/modwrt/raw/main/sysinfo && chmod +x /usr/bin/sysinfo
wget -O /etc/profile https://raw.githubusercontent.com/andrygibhq/modwrt/raw/main/profile && chmod 0644 /etc/profile
